import jsPDF from 'jspdf';
import type { Expense, CategoryDef, User } from '../store/useStore';

export async function exportToPDF(expenses: Expense[], categories: CategoryDef[], user: User | null) {
    // Create new PDF document
    const doc = new jsPDF();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('Finance VA - Expense Report', 14, 22);

    // Header Info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by: ${user?.name ?? 'User'}`, 14, 30);
    doc.text(`Email: ${user?.email ?? 'N/A'}`, 14, 36);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 42);

    // Summary line
    const total = expenses.reduce((sum, e) => sum + e.amount, 0);
    doc.setFontSize(14);
    doc.setTextColor(20, 20, 20);
    doc.text(`Total Recorded Spending: ${total.toFixed(2)}`, 14, 56);

    // Table Header
    doc.setFontSize(10);
    doc.setFillColor(243, 244, 246);
    doc.rect(14, 64, 182, 10, 'F');
    doc.setTextColor(80, 80, 80);
    doc.setFont('helvetica', 'bold');
    doc.text('Date', 18, 71);
    doc.text('Merchant', 60, 71);
    doc.text('Category', 130, 71);
    doc.text('Amount', 170, 71);

    // Table Rows
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
    let y = 84;

    // Sort by recent first
    const sorted = [...expenses].sort((a, b) => b.purchaseAt.localeCompare(a.purchaseAt));

    sorted.forEach((e) => {
        if (y > 275) {
            doc.addPage();
            y = 20;
        }

        const cat = categories.find(c => c.key === e.category)?.label ?? e.category;

        doc.text(new Date(e.purchaseAt).toLocaleDateString(), 18, y);
        doc.text(e.merchant.length > 30 ? e.merchant.slice(0, 30) + '...' : e.merchant, 60, y);
        doc.text(cat.length > 15 ? cat.slice(0, 15) + '...' : cat, 130, y);
        doc.text(`${e.amount.toFixed(2)} ${e.currency}`, 170, y);

        // simple row divider
        doc.setDrawColor(230, 230, 230);
        doc.line(14, y + 3, 196, y + 3);

        y += 10;
    });

    // Save locally
    doc.save('FinanceVA_Report.pdf');
}
